nome = str(input('Digite o nome completo: '))
mai = nome.upper()
min = nome.lower()
qtslts = len(nome.replace(' ',''))
qtspri = nome.split()
pri = len(qtspri[0])
print('O nome {}'.format(nome))
print('Maisculo {}'.format(mai))
print('Minusculo {}'.format(min))
print('Qunatidade de letras {}'.format(qtslts))
print('Quantidade letras primeiro nome {}'.format(pri))